language:
 - java

before_script:
 - wget www.jibble.org/files/pircbot-1.5.0.zip
 - unzip pircbot-1.5.0.zip
 - ls
 - cp -r pircbot-1.5.0/* .
 - ls

script: make

notifications:
  email: false
  irc:
  - "chat.freenode.net##rschen7754"
  - "chat.freenode.net#wikipedia-en-roads-rc"
  on_success: always

