language:
 - java

before_script:
 - wget www.jibble.org/files/pircbot-1.5.0.zip
 - unzip pircbot-1.5.0.zip
 - cp -r pircbot-1.5.0/* .

script: make

notifications:
  email: false
  irc:
  - "chat.freenode.net##rschen7754"
  - "chat.freenode.net#wikipedia-en-roads-rc"
  on_success: change
  on_failure: always

